version: 2
jobs:
  test:
    machine:
      - image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          command: |
            cd .circleci && ./run-tests.sh

  # publish jobs require $DOCKERHUB_REPO, $DOCKERHUB_USER, $DOCKERHUB_PASS defined

  docker:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            LATEST_TAG=${CIRCLE_TAG:1} #trim v from tag
            docker buildx create --use
            docker buildx build -t $DOCKERHUB_REPO:$LATEST_TAG --platform linux/amd64,linux/arm64,linux/arm/v7 --push .

workflows:
  version: 2
  build_and_test:
    jobs:
      - test

  publish:
    jobs:
      - docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
